# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
# breeds=[
# ["Afghan Hound","Dog"],
# ["American FoxHound","Dog"],
# ["Australian Shephard","Dog"],
# ["First Breed","Cat"],
# ["Second Breed","Cat"]

# ]
# breeds.each do |name,pet_name|
#   Breed.create(name:name,pet_name:pet_name)
# end
# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
breeds=[
    ["Cross","Dog"],
    ["Indie","Dog"],
    ["Mix","Dog"],
    ["Mongrel","Dog"],
    ["Affenpinscher","Dog"],
    ["Afghan Hound","Dog"],
    ["Airedale Terrier","Dog"],
    ["Akita","Dog"],
    ["Alaskan Malamute","Dog"],
    ["American Eskimo Dog","Dog"],
    ["American Foxhound","Dog"],
    ["American Staffordshire Terrier","Dog"],
    ["American Water Spaniel","Dog"],
    ["Anatolian Shepherd Dog","Dog"],
    ["Australian Cattle Dog","Dog"],
    ["Australian Shepherd","Dog"],
    ["Australian Terrier","Dog"],
    ["Basenji","Dog"],
    ["Basset Hound","Dog"],
    ["Beagle","Dog"],
    ["Bearded Collie","Dog"],
    ["Beauceron","Dog"],
    ["Bedlington Terrier","Dog"],
    ["Belgian Malinois","Dog"],
    ["Belgian Sheepdog","Dog"],
    ["Belgian Tervuren","Dog"],
    ["Bernese Mountain Dog","Dog"],
    ["Bichon Frise","Dog"],
    ["Black and Tan Coonhound","Dog"],
    ["Black Russian Terrier","Dog"],
    ["Bloodhound","Dog"],
    ["Border Collie","Dog"],
    ["Border Terrier","Dog"],
    ["Borzoi","Dog"],
    ["Boston Terrier","Dog"],
    ["Bouvier des Flandres","Dog"],
    ["Boxer","Dog"],
    ["Briard","Dog"],
    ["Brittany","Dog"],
    ["Brussels Griffon","Dog"],
    ["Bulldog","Dog"],
    ["Bullmastiff","Dog"],
    ["Bull Terrier","Dog"],
    ["Cairn Terrier","Dog"],
    ["Canaan Dog","Dog"],
    ["Cardigan Welsh Corgi","Dog"],
    ["Cavalier King Charles Spaniel","Dog"],
    ["Chesapeake Bay Retriever","Dog"],
    ["Chihuahua","Dog"],
    ["Chinese Crested","Dog"],
    ["Chinese Shar-Pei","Dog"],
    ["Chow Chow","Dog"],
    ["Clumber Spaniel","Dog"],
    ["Cocker Spaniel","Dog"],
    ["Collie","Dog"],
    ["Curly-Coated Retriever","Dog"],
    ["Dachshund","Dog"],
    ["Dalmatian","Dog"],
    ["Dandie Dinmont Terrier","Dog"],
    ["Doberman Pinscher","Dog"],
    ["Dogue de Bordeaux","Dog"],
    ["English Cocker Spaniel","Dog"],
    ["English Foxhound","Dog"],
    ["English Setter","Dog"],
    ["English Springer Spaniel","Dog"],
    ["English Toy Spaniel","Dog"],
    ["Field Spaniel","Dog"],
    ["Finnish Spitz","Dog"],
    ["Flat-Coated Retriever","Dog"],
    ["French Bulldog","Dog"],
    ["German Pinscher","Dog"],
    ["German Shepherd Dog","Dog"],
    ["German Shorthaired Pointer","Dog"],
    ["German Wirehaired Pointer","Dog"],
    ["Giant Schnauzer","Dog"],
    ["Glen of Imaal Terrier","Dog"],
    ["Golden Retriever","Dog"],
    ["Gordon Setter","Dog"],
    ["Great Dane","Dog"],
    ["Greater Swiss Mountain Dog","Dog"],
    ["Great Pyrenees","Dog"],
    ["Greyhound","Dog"],
    ["Harrier","Dog"],
    ["Havanese","Dog"],
    ["Ibizan Hound","Dog"],
    ["Irish Setter","Dog"],
    ["Irish Terrier","Dog"],
    ["Irish Water Spaniel","Dog"],
    ["Irish Wolfhound","Dog"],
    ["Italian Greyhound","Dog"],
    ["Jack Russell Terrier","Dog"],
    ["Japanese Chin","Dog"],
    ["Keeshond","Dog"],
    ["Kerry Blue Terrier","Dog"],
    ["Komondor","Dog"],
    ["Kuvasz","Dog"],
    ["Labrador Retriever","Dog"],
    ["Lakeland Terrier","Dog"],
    ["Lhasa Apso","Dog"],
    ["Lowchen","Dog"],
    ["Maltese","Dog"],
    ["Standard Manchester Terrier","Dog"],
    ["Mastiff","Dog"],
    ["Miniature Bull Terrier","Dog"],
    ["Miniature Pinscher","Dog"],
    ["Miniature Schnauzer","Dog"],
    ["Neapolitan Mastiff","Dog"],
    ["Newfoundland","Dog"],
    ["Norfolk Terrier","Dog"],
    ["Norwegian Elkhound","Dog"],
    ["Norwich Terrier","Dog"],
    ["Nova Scotia Duck Tolling Retriever","Dog"],
    ["Old English Sheep Dog","Dog"],
    ["Otterhound","Dog"],
    ["Papillon","Dog"],
    ["Parson Russell Terrier","Dog"],
    ["Pekingese","Dog"],
    ["Pembroke Welsh Corgi","Dog"],
    ["Petit Basset Griffon Vendeen","Dog"],
    ["Pharaoh Hound","Dog"],
    ["Plott","Dog"],
    ["Pointer","Dog"],
    ["Polish Lowland Sheepdog","Dog"],
    ["Pomeranian","Dog"],
    ["Portuguese Water Dog","Dog"],
    ["Pug","Dog"],
    ["Puli","Dog"],
    ["Rhodesian Ridgeback","Dog"],
    ["Rottweiler","Dog"],
    ["Saint Bernard","Dog"],
    ["Saluki","Dog"],
    ["Samoyed","Dog"],
    ["Schipperke","Dog"],
    ["Scottish Deerhound","Dog"],
    ["Scottish Terrier","Dog"],
    ["Sealyham Terrier","Dog"],
    ["Shetland Sheepdog","Dog"],
    ["Shiba Inu","Dog"],
    ["Shih Tzu","Dog"],
    ["Siberian Husky","Dog"],
    ["Silky Terrier","Dog"],
    ["Skye Terrier","Dog"],
    ["Smooth Fox Terrier","Dog"],
    ["Soft Coated Wheaten Terrier","Dog"],
    ["Spinone Italiano","Dog"],
    ["Staffordshire Bull Terrier","Dog"],
    ["Standard Poodle","Dog"],
    ["Standard Schnauzer","Dog"],
    ["Sussex Spaniel","Dog"],["Swedish Vallhund","Dog"],["Tibetan Mastiff","Dog"],["Tibetan Spaniel","Dog"],["Tibetan Terrier","Dog"],["Toy Fox Terrier","Dog"],["Toy Manchester Terrier","Dog"],["Toy Poodle","Dog"],["Vizsla","Dog"],["Weimaraner","Dog"],["Welsh Springer Spaniel","Dog"],["Welsh Terrier","Dog"],["West Highland White Terrier","Dog"],["Whippet","Dog"],["Wire Fox Terrier","Dog"],["Wirehaired Pointing Griffon","Dog"],["Yorkshire Terrier","Dog"],["Abyssinian","Cat"],
    ["American Bobtail","Cat"],
    ["American Curl","Cat"],
    ["American Shorthair","Cat"],
    ["American Wirehair","Cat"],
    ["Balinese","Cat"],
    ["Bengal Cats","Cat"],
    ["Birman","Cat"],
    ["Bombay","Cat"],
    ["British Shorthair","Cat"],
    ["Burmese","Cat"],
    ["Burmilla","Cat"],
    ["Chartreux","Cat"],
    ["Chinese Li Hua","Cat"],
    ["Colorpoint Shorthair","Cat"],
    ["Cornish Rex","Cat"],
    ["Cymric","Cat"],
    ["Devon Rex","Cat"],
    ["Egyptian Mau","Cat"],
    ["European Burmese","Cat"],
    ["Exotic","Cat"],
    ["Havana Brown","Cat"],
    ["Himalayan","Cat"],
    ["Japanese Bobtail","Cat"],
    ["Javanese","Cat"],
    ["Korat","Cat"],
    ["LaPerm","Cat"],
    ["Maine Coon","Cat"],
    ["Manx","Cat"],
    ["Nebelung","Cat"],
    ["Norwegian Forest","Cat"],
    ["Ocicat","Cat"],
    ["Oriental","Cat"],
    ["Persian","Cat"],
    ["Ragamuffin","Cat"],
    ["Ragdoll","Cat"],
    ["Russian Blue","Cat"],
    ["Savannah","Cat"],
    ["Scottish Fold","Cat"],
    ["Selkirk Rex","Cat"],
    ["Siamese Cat","Cat"],
    ["Siberian","Cat"],
    ["Singapura","Cat"],
    ["Snowshoe","Cat"],
    ["Somali","Cat"],
    ["Somali","Cat"],
    ["Sphynx","Cat"],
    ["Tonkinese","Cat"],
    ["Turkish Angora","Cat"],
    ["Turkish Van","Cat"]
]
breeds.each do |name,pet_name|
    Breed.create(name:name,pet_name:pet_name)
end





