# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
# breeds=[
# ["Afghan Hound","Dog"],
# ["American FoxHound","Dog"],
# ["Australian Shephard","Dog"],
# ["First Breed","Cat"],
# ["Second Breed","Cat"]

# ]
# breeds.each do |name,pet_name|
#   Breed.create(name:name,pet_name:pet_name)
# end
# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

breeds=[
    ["Cross","Dog"],
    ["Indie","Dog"],
    ["Mix","Dog"],
    ["Mongrel","Dog"],
    ["Affenpinscher","Dog"],
    ["Afghan Hound","Dog"],
    ["Airedale Terrier","Dog"],
    ["Akita","Dog"],
    ["Alaskan Malamute","Dog"],
    ["American Eskimo Dog","Dog"],
    ["American Foxhound","Dog"],
    ["American Staffordshire Terrier","Dog"],
    ["American Water Spaniel","Dog"],
    ["Anatolian Shepherd Dog","Dog"],
    ["Australian Cattle Dog","Dog"],
    ["Australian Shepherd","Dog"],
    ["Australian Terrier","Dog"],
    ["Basenji","Dog"],
    ["Basset Hound","Dog"],
    ["Beagle","Dog"],
    ["Bearded Collie","Dog"],
    ["Beauceron","Dog"],
    ["Bedlington Terrier","Dog"],
    ["Belgian Malinois","Dog"],
    ["Belgian Sheepdog","Dog"],
    ["Belgian Tervuren","Dog"],
    ["Bernese Mountain Dog","Dog"],
    ["Bichon Frise","Dog"],
    ["Black and Tan Coonhound","Dog"],
    ["Black Russian Terrier","Dog"],
    ["Bloodhound","Dog"],
    ["Border Collie","Dog"],
    ["Border Terrier","Dog"],
    ["Borzoi","Dog"],
    ["Boston Terrier","Dog"],
    ["Bouvier des Flandres","Dog"],
    ["Boxer","Dog"],
    ["Briard","Dog"],
    ["Brittany","Dog"],
    ["Brussels Griffon","Dog"],
    ["Bulldog","Dog"],
    ["Bullmastiff","Dog"],
    ["Bull Terrier","Dog"],
    ["Cairn Terrier","Dog"],
    ["Canaan Dog","Dog"],
    ["Cardigan Welsh Corgi","Dog"],
    ["Cavalier King Charles Spaniel","Dog"],
    ["Chesapeake Bay Retriever","Dog"],
    ["Chihuahua","Dog"],
    ["Chinese Crested","Dog"],
    ["Chinese Shar-Pei","Dog"],
    ["Chow Chow","Dog"],
    ["Clumber Spaniel","Dog"],
    ["Cocker Spaniel","Dog"],
    ["Collie","Dog"],
    ["Curly-Coated Retriever","Dog"],
    ["Dachshund","Dog"],
    ["Dalmatian","Dog"],
    ["Dandie Dinmont Terrier","Dog"],
    ["Doberman Pinscher","Dog"],
    ["Dogue de Bordeaux","Dog"],
    ["English Cocker Spaniel","Dog"],
    ["English Foxhound","Dog"],
    ["English Setter","Dog"],
    ["English Springer Spaniel","Dog"],
    ["English Toy Spaniel","Dog"],
    ["Field Spaniel","Dog"],
    ["Finnish Spitz","Dog"],
    ["Flat-Coated Retriever","Dog"],
    ["French Bulldog","Dog"],
    ["German Pinscher","Dog"],
    ["German Shepherd Dog","Dog"],
    ["German Shorthaired Pointer","Dog"],
    ["German Wirehaired Pointer","Dog"],
    ["Giant Schnauzer","Dog"],
    ["Glen of Imaal Terrier","Dog"],
    ["Golden Retriever","Dog"],
    ["Gordon Setter","Dog"],
    ["Great Dane","Dog"],
    ["Greater Swiss Mountain Dog","Dog"],
    ["Great Pyrenees","Dog"],
    ["Greyhound","Dog"],
    ["Harrier","Dog"],
    ["Havanese","Dog"],
    ["Ibizan Hound","Dog"],
    ["Irish Setter","Dog"],
    ["Irish Terrier","Dog"],
    ["Irish Water Spaniel","Dog"],
    ["Irish Wolfhound","Dog"],
    ["Italian Greyhound","Dog"],
    ["Jack Russell Terrier","Dog"],
    ["Japanese Chin","Dog"],
    ["Keeshond","Dog"],
    ["Kerry Blue Terrier","Dog"],
    ["Komondor","Dog"],
    ["Kuvasz","Dog"],
    ["Labrador Retriever","Dog"],
    ["Lakeland Terrier","Dog"],
    ["Lhasa Apso","Dog"],
    ["Lowchen","Dog"],
    ["Maltese","Dog"],
    ["Standard Manchester Terrier","Dog"],
    ["Mastiff","Dog"],
    ["Miniature Bull Terrier","Dog"],
    ["Miniature Pinscher","Dog"],
    ["Miniature Schnauzer","Dog"],
    ["Neapolitan Mastiff","Dog"],
    ["Newfoundland","Dog"],
    ["Norfolk Terrier","Dog"],
    ["Norwegian Elkhound","Dog"],
    ["Norwich Terrier","Dog"],
    ["Nova Scotia Duck Tolling Retriever","Dog"],
    ["Old English Sheep Dog","Dog"],
    ["Otterhound","Dog"],
    ["Papillon","Dog"],
    ["Parson Russell Terrier","Dog"],
    ["Pekingese","Dog"],
    ["Pembroke Welsh Corgi","Dog"],
    ["Petit Basset Griffon Vendeen","Dog"],
    ["Pharaoh Hound","Dog"],
    ["Plott","Dog"],
    ["Pointer","Dog"],
    ["Polish Lowland Sheepdog","Dog"],
    ["Pomeranian","Dog"],
    ["Portuguese Water Dog","Dog"],
    ["Pug","Dog"],
    ["Puli","Dog"],
    ["Rhodesian Ridgeback","Dog"],
    ["Rottweiler","Dog"],
    ["Saint Bernard","Dog"],
    ["Saluki","Dog"],
    ["Samoyed","Dog"],
    ["Schipperke","Dog"],
    ["Scottish Deerhound","Dog"],
    ["Scottish Terrier","Dog"],
    ["Sealyham Terrier","Dog"],
    ["Shetland Sheepdog","Dog"],
    ["Shiba Inu","Dog"],
    ["Shih Tzu","Dog"],
    ["Siberian Husky","Dog"],
    ["Silky Terrier","Dog"],
    ["Skye Terrier","Dog"],
    ["Smooth Fox Terrier","Dog"],
    ["Soft Coated Wheaten Terrier","Dog"],
    ["Spinone Italiano","Dog"],
    ["Staffordshire Bull Terrier","Dog"],
    ["Standard Poodle","Dog"],
    ["Standard Schnauzer","Dog"],
    ["Sussex Spaniel","Dog"],["Swedish Vallhund","Dog"],["Tibetan Mastiff","Dog"],["Tibetan Spaniel","Dog"],["Tibetan Terrier","Dog"],["Toy Fox Terrier","Dog"],["Toy Manchester Terrier","Dog"],["Toy Poodle","Dog"],["Vizsla","Dog"],["Weimaraner","Dog"],["Welsh Springer Spaniel","Dog"],["Welsh Terrier","Dog"],["West Highland White Terrier","Dog"],["Whippet","Dog"],["Wire Fox Terrier","Dog"],["Wirehaired Pointing Griffon","Dog"],["Yorkshire Terrier","Dog"],["Abyssinian","Cat"],
    ["Cross","Dog"],
    ["Indie","Dog"],
    ["Mix","Dog"],
    ["Mongrel","Dog"],
    ["American Bobtail","Cat"],
    ["American Curl","Cat"],
    ["American Shorthair","Cat"],
    ["American Wirehair","Cat"],
    ["Balinese","Cat"],
    ["Bengal Cats","Cat"],
    ["Birman","Cat"],
    ["Bombay","Cat"],
    ["British Shorthair","Cat"],
    ["Burmese","Cat"],
    ["Burmilla","Cat"],
    ["Chartreux","Cat"],
    ["Chinese Li Hua","Cat"],
    ["Colorpoint Shorthair","Cat"],
    ["Cornish Rex","Cat"],
    ["Cymric","Cat"],
    ["Devon Rex","Cat"],
    ["Egyptian Mau","Cat"],
    ["European Burmese","Cat"],
    ["Exotic","Cat"],
    ["Havana Brown","Cat"],
    ["Himalayan","Cat"],
    ["Japanese Bobtail","Cat"],
    ["Javanese","Cat"],
    ["Korat","Cat"],
    ["LaPerm","Cat"],
    ["Maine Coon","Cat"],
    ["Manx","Cat"],
    ["Nebelung","Cat"],
    ["Norwegian Forest","Cat"],
    ["Ocicat","Cat"],
    ["Oriental","Cat"],
    ["Persian","Cat"],
    ["Ragamuffin","Cat"],
    ["Ragdoll","Cat"],
    ["Russian Blue","Cat"],
    ["Savannah","Cat"],
    ["Scottish Fold","Cat"],
    ["Selkirk Rex","Cat"],
    ["Siamese Cat","Cat"],
    ["Siberian","Cat"],
    ["Singapura","Cat"],
    ["Snowshoe","Cat"],
    ["Somali","Cat"],
    ["Somali","Cat"],
    ["Sphynx","Cat"],
    ["Tonkinese","Cat"],
    ["Turkish Angora","Cat"],
    ["Turkish Van","Cat"]
]
cities=[
    "Abohar",
    "Achalpur",
    "Adilabad",
    "Adityapur",
    "Adoni",
    "Agartala",
    "Agra",
    "Agra Cantonment",
    "Ahmadnagar",
    "Ahmedabad",
    "Aizawl",
    "Ajmer",
    "Akola",
    "Akot",
    "Alandur",
    "Alappuzha",
    "Aligarh",
    "Alipurduar",
    "Allahabad",
    "Along",
    "Alwal",
    "Alwar",
    "Amalapuram",
    "Amalner",
    "Ambajogai",
    "Ambala",
    "Ambala Cantonment",
    "Ambala Sadar",
    "Ambarnath",
    "Ambasamudram",
    "Ambattur",
    "Ambikapur",
    "Ambur",
    "Amravati",
    "Amreli",
    "Amritsar",
    "Amroha",
    "Anakapalle",
    "Anand",
    "Anantapur",
    "Anantnag",
    "Anjangaon",
    "Anjar",
    "Anklesvar",
    "Ara",    
    "Arakkonam",
    "Arambagh",
    "Arani",
    "Araria",
    "Arcot",
    "Aruppukkottai",
    "Asansol",
    "Ashokenagar-Kalyangarh",
    "Ashoknagar",
    "Attur",
    "Auraiya",
    "Aurangabad",
    "Aurangabad",
    "Avadi",
    "Avaniapuram",
    "Azamgarh",
    "Badlapur",
    "Baduna",
    "Bagaha",
    "Bagalkot",
    "Bagbera",
    "Bahadurgarh",
    "Baharampore",
    "Baheri",
    "Bahraich",
    "Baidyabati",
    "Balaghat",
    "Balangir",
    "Baleshwar",
    "Ballarpur",
    "Ballia",
    "Bally",
    "Balotra",
    "Balrampur",
    "Balurghat",
    "Banda",
    "Bangalore",
    "Bankura",
    "Bansberia",
    "Banswara",
    "Bapatla",
    "Baramati",
    "Baramula",
    "Baran",
    "Baranagar",
    "Barasat",
    "Baraut",
    "Barbil",
    "Bardhaman",
    "Bardoli",
    "Bareilly",
    "Bargarh",
    "Bari",
    "Baripada",
    "Barmer",
    "Barnala",
    "Barrackpore",
    "Barsi",
    "Baruipur",
    "Basavakalyan",
    "Basirhat",
    "Basmat",
    "Basoda",
    "Basti",
    "Batala",
    "Bathinda",
    "Beawar",
    "Begusarai",
    "Behta Hazipur",
    "Bela Pratapgarh",
    "Beldanga",
    "Belgaum",
    "Bellampalle",
    "Bellary",
    "Berhmapur",
    "Bettiah",
    "Betul",
    "Beypore",
    "Bhadohi",
    "Bhadrak",
    "Bhadravati",
    "Bhadravati",
    "Bhadreswar",
    "Bhagalpur",
    "Bhandara",
    "Bharatpur",
    "Bharuch",
    "Bhatapara",
    "Bhatpara",
    "Bhavani",
    "Bhavnagar",
    "Bhawanipatna",
    "Bhilai",
    "Bhilai Charoda",
    "Bhilwara",
    "Bhimavaram",
    "Bhind",
    "Bhiwandi",
    "Bhiwani",
    "Bhopal",
    "Bhubaneshwar",
    "Bhuj",
    "Bhuli",
    "Bhusawal",
    "Bid",
    "Bidar",
    "Bidhannagar",
    "Bihar",
    "Bijapur",
    "Bijnor",
    "Bikaner",
    "Bilaspur",
    "Bilimora",
    "Bina Etawa",
    "Birnagar",
    "Bisalpur",
    "Bishnupur",
    "Bobbili",
    "Bodhan",
    "Bodinayakanur",
    "Bokaro Steel City",
    "Bolpur",
    "Bommanahalli",
    "Bongaigaon",
    "Bongaon",
    "Borsad",
    "Botad",
    "Brajarajnagar",
    "Budaun",
    "Budge",
    "Bulandshahr",
    "Buldana",
    "Bundi",
    "Burhanpur",
    "Burhar Dhanpuri",
    "Buxar",
    "Byatarayanapura",
    "Chaibasa",
    "Chakdah",
    "Chakradharpur",
    "Chalisgaon",
    "Champdani",
    "Chamrajnagar",
    "Chandannagar",
    "Chandausi",
    "Chandigarh",
    "Chandkheda",
    "Chandlodiya",
    "Chandpur",
    "Chandrapur",
    "Chandrokona",
    "Changanacheri",
    "Channapatna",
    "Chapra",
    "Chas",
    "Chengalpattu",
    "Chennai",
    "Cherthala",
    "Cheruvannur",
    "Chhatarpur",
    "Chhibramau",
    "Chhindwara",
    "Chidambaram",
    "Chikballapur",
    "Chikmagalur",
    "Chilakalurupet",
    "Chinnachowk",
    "Chintamani",
    "Chirala",
    "Chirkunda",
    "Chirmiri",
    "Chitradurga",
    "Chittoor",
    "Chittorgarh",
    "Chittur",
    "Chomun",
    "Chopda",
    "Churachandpur",
    "Churu",
    "Civil Township",
    "Coimbatore",
    "Contai",
    "Cooch Behar",
    "Coonoor",
    "Coopers Camp",
    "Cuddalore",
    "Cuddapah",
    "Cumbum",
    "Cuttack",
    "Dabhoi",
    "Dabra",
    "Dadra",
    "Dadri",
    "Dahod",
    "Dainhata",
    "Dalkhola",
    "Dalli Rajhara",
    "Daltonganj",
    "Daman",
    "Damoh",
    "Dandeli",
    "Darbhanga",
    "Darjeeling",
    "Dasarahalli",
    "Datia",
    "Dausa",
    "Davanagere",
    "Dehradun",
    "Dehri",
    "Delhi",
    "Deoband",
    "Deoghar",
    "Deolali",
    "Deoria",
    "Devarshola",
    "Dewas",
    "Dhamtari",
    "Dhanbad",
    "Dhar",
    "Dharapuram",
    "Dharmapuri",
    "Dharmavaram",
    "Dhaulpur",
    "Dhenkanal",
    "Dholka",
    "Dhoraji",
    "Dhrangadhra",
    "Dhubri",
    "Dhule",
    "Dhulian",
    "Dhupguri",
    "Diamond Harbour",
    "Dibrugarh",
    "Diglipur",
    "Dimapur",
    "Dinapur Nizamat",
    "Dindigul",
    "Diphu",
    "Disa",
    "Dispur",
    "Diu",
    "Dmhata",
    "Dod Ballapur",
    "Dombivali",
    "Dubrajpur",
    "Dum",
    "Durgapur",
    "Durg-Bhilainagar",
    "Edathala",
    "Egra",
    "Eluru",
    "English Bazar",
    "Erode",
    "Etah",
    "Etawah",
    "Faizabad",
    "Faridabad (New Township)",
    "Faridkot",
    "Faridpur",
    "Farrukhabad",
    "Fatehabad",
    "Fatehpur",
    "Fatehpur",
    "Fazilka",
    "Firozabad",
    "Firozepur",
    "Firozpur Cantonment",
    "Gadag",
    "Gaddiannaram",
    "Gadwal",
    "Gajuwaka",
    "Gandhidham",
    "Gandhinagar",
    "Gangaghat",
    "Gangapur",
    "Gangarampore",
    "Gangawati",
    "Gangoh",
    "Gangtok",
    "Garulia",
    "Gaya",
    "Gayeshpur",
    "Geyzing",
    "Ghatal",
    "Ghatlodiya",
    "Ghaziabad",
    "Ghazipur",
    "Giridih",
    "Gobardanga",
    "Gobichettipalayam",
    "Gobindgarh",
    "Godhra",
    "Gokak",
    "Gola Gokarannath",
    "Gonda",
    "Gondal",
    "Gondia",
    "Gopalganj",
    "Gorakhpur",
    "Gudivada",
    "Gudiyatham",
    "Gudur",
    "Gulbarga",
    "Guna",
    "Guntakal",
    "Guntur",
    "Gurdaspur",
    "Gurgaon",
    "Guruvayur",
    "Gushkara",
    "Guwahati",
    "Gwalior",
    "Habra",
    "Hajipur",
    "Haldia",
    "Haldibari",
    "Haldwani",
    "Halisahar",
    "Hansi",
    "Hanumangarh",
    "Hapur",
    "Harda",
    "Hardoi",
    "Haridwar",
    "Harihar",
    "Hasanpur",
    "Hassan",
    "Hathras",
    "Haveri",
    "Hazaribagh",
    "Himatnagar",
    "Hindon",
    "Hindupur",
    "Hinganghat",
    "Hingoli",
    "Hissar",
    "Hooghly-Chinsurah",
    "Hoshangabad",
    "Hoshiarpur",
    "Hospet",
    "Hosur",
    "Howrah",
    "Hubli",
    "Hyderabad",
    "Ichalkaranji",
    "Ilkal",
    "Imphal",
    "Indore",
    "Islampur",
    "Itanagar",
    "Itarsi",
    "Jabalpur",
    "Jabalpur Cantonment",
    "Jagadhri",
    "Jagdalpur",
    "Jagraon",
    "Jagtial",
    "Jahangirabad",
    "Jainagar-Mazilpore",
    "Jaipur",
    "Jaisalmer",
    "Jalandhar",
    "Jalaun",
    "Jalgaon",
    "Jalna",
    "Jalpaiguri",
    "Jalpaiguri",
    "Jamalpur",
    "Jamkhandi",
    "Jammu",
    "Jamnagar",
    "Jamshedpur",
    "Jamui",
    "Jamuria",
    "Jangipore",
    "Jaora",
    "Jatani",
    "Jaunpur",
    "Jaypore",
    "Jehanabad",
    "Jetpur",
    "Jhaldah",
    "Jhansi",
    "Jhargram",
    "Jharia",
    "Jharsuguda",
    "Jhunjhunun",
    "Jiaganj-Azimganj",
    "Jind",
    "Jodhpur",
    "Jorapokhar",
    "Jorhat",
    "Jumri Tilaiya",
    "Junagadh",
    "Kadayanallur",
    "Kadi",
    "Kadiri",
    "Kagaznagar",
    "Kairana",
    "Kaithal",
    "Kakinada",
    "Kalamassery",
    "Kaliaganj",
    "Kalimpong",
    "Kallur",
    "Kalna",
    "Kalol",
    "Kalyan",
    "Kalyani",
    "Kamareddy",
    "Kamarhati",
    "Kamthi",
    "Kanchipuram",
    "Kanchrapara",
    "Kandi",
    "Kandukur",
    "Kanhangad",
    "Kannauj",
    "Kannur",
    "Kanpur",
    "Kanpur Cantonment",
    "Kapra",
    "Kapurthala",
    "Karad",
    "Karaikal",
    "Karaikkudi",
    "Karanja",
    "Karauli",
    "Karimganj",
    "Karimnagar",
    "Karnal",
    "Karur",
    "Karwar",
    "Kasaragod",
    "Kasganj",
    "Kashipur",
    "Kasipalayam",
    "Kathua",
    "Katihar",
    "Katras",
    "Katwa",
    "Kavali",
    "Kavaratti",
    "Kayamkulam",
    "Kendujhar",
    "Keshod",
    "Khadki",
    "Khambhat",
    "Khamgaon",
    "Khammam",
    "Khandwa",
    "Khanna",
    "Kharagpur",
    "Kharar",
    "Khardah",
    "Khargone",
    "Khatauli",
    "Khirpai",
    "Khopoli",
    "Khurja",
    "Kiratpur",
    "Kishanganj",
    "Kishangarh",
    "Kochi",
    "Kodungallur",
    "Kohima",
    "Kolar",
    "Kolhapur",
    "Kolkata",
    "Kollam",
    "Kollegal",
    "Komarapalayam",
    "Konch",
    "Konnagar",
    "Kopargaon",
    "Koppal",
    "Koratla",
    "Korba",
    "Kota",
    "Kotkapura",
    "Kottagudem",
    "Kottayam",
    "Kovilpatti",
    "Kozhikode",
    "Krishnagiri",
    "Krishnanagar",
    "Krishnarajapura",
    "Kuchaman City",
    "Kukatpally",
    "Kulti",
    "Kumbakonam",
    "Kuniyamuthur",
    "Kunnamkulam",
    "Kurichi",
    "Kurnool",
    "Kurseong",
    "Kurukshetra",
    "Ladnun",
    "Laharpur",
    "Lakhimpur",
    "Lakhisarai",
    "Lalitpur",
    "Latur",
    "LB Nagar",
    "Lonavale",
    "Loni",
    "Lucknow",
    "Lucknow Cantonment",
    "Ludhiana",
    "Lumding",
    "Lunglei",
    "Machhiwara Sahib",
    "Machilipatnam",
    "Madanapalle",
    "Madavaram",
    "Madgaon",
    "Madhubani",
    "Madhyamgram",
    "Madurai",
    "Mahadevapura",
    "Mahbubnagar",
    "Mahesana",
    "Maheshtala",
    "Mahoba",
    "Mahuva",
    "Mainpuri",
    "Makrana",
    "Mal",
    "Malappuram",
    "Malegaon",
    "Maler Kotla",
    "Malkajgiri",
    "Malkapur",
    "Malout",
    "Mancherial",
    "Mandamarri",
    "Mandi",
    "Mandi Dabwali",
    "Mandla",
    "Mandsaur",
    "Mandvi",
    "Mandya",
    "Mangalagiri",
    "Mangalore",
    "Mango",
    "Mangrol",
    "Manjeri",
    "Manmad",
    "Mannargudi",
    "Mansa",
    "Markapur",
    "Mathabhanga",
    "Mathura",
    "Mau Ranipur",
    "Maunath Bhanjan",
    "Mawana",
    "Mayiladuthurai",
    "Medinipur",
    "Meerut",
    "Meerut Cantonment",
    "Mekliganj",
    "Memari",
    "Mettupalayam",
    "Mettur",
    "Mhow",
    "Mira Bhayandar",
    "Miraj",
    "Mirik",
    "Miryalguda",
    "Mirzapur",
    "Modasa",
    "Modinagar",
    "Moga",
    "Mohali",
    "Mokama",
    "Moradabad",
    "Morbi",
    "Morena",
    "Mormugao",
    "Motihari",
    "Mubarakpur",
    "Mughalsarai",
    "Mumbai",
    "Munger",
    "Muradnagar",
    "Murshidabad",
    "Murwara",
    "Muzaffarnagar",
    "Muzaffarpur",
    "Mysore",
    "Nabadwip",
    "Nabha",
    "Nadiad",
    "Nagaon",
    "Nagapattinam",
    "Nagaur",
    "Nagda",
    "Nagercoil",
    "Nagina",
    "Nagpur",
    "Naihati",
    "Najibabad",
    "Nalasopara",
    "Nalgonda",
    "Nalhati",
    "Namakkal",
    "Nanded",
    "Nandurbar",
    "Nandyal",
    "Narasaraopet",
    "Narnaul",
    "Narsapur",
    "Narsimhapur",
    "Narwana",
    "Nashik",
    "NavgharManikpur",
    "Navi Mumbai",
    "Navsari",
    "Nawabganj",
    "Nawada",
    "Nawalgarh",
    "Nedumangad",
    "Nellore",
    "New Barrackpore",
    "Neyveli",
    "Neyyattinkara",
    "Nimach",
    "Nimbahera",
    "Nipani",
    "Nirmal",
    "Nizamabad",
    "Noida",
    "North Barrackpore",
    "North Dum Dum",
    "North Lakhimpur",
    "Nuzvid",
    "Obra",
    "Old Malda",
    "Ongole",
    "Ooty",
    "Orai",
    "Osmanabad",
    "Oulgaret",
    "Palacole",
    "Palakkad",
    "Palani",
    "Palanpur",
    "Palghar",
    "Pali",
    "Palitana",
    "Pallavaram",
    "Palwal",
    "Palwancha",
    "Panaji",
    "Panchkula",
    "Pandharpur",
    "Panihati",
    "Panipat",
    "Panna",
    "Panruti",
    "Panskura",
    "Panvel",
    "Paradip",
    "Paramakudi",
    "Parasia",
    "Parbhani",
    "Parli",
    "Patan",
    "Pathankot",
    "Patiala",
    "Patna",
    "Pattanagere",
    "Pattukkottai",
    "Payyannur",
    "Petlad",
    "Phagwara",
    "Phaltan",
    "Phulwari Sharif",
    "Phusro",
    "Pilibhit",
    "Pilkhuwa",
    "Pimpri-Chinchwad",
    "Pitapuram",
    "Pithampur",
    "Pollachi",
    "Ponnani",
    "Ponnur",
    "Porbandar",
    "Port Blair",
    "Proddatur",
    "Puducherry",
    "Pudukkottai",
    "Pujali",
    "Puliyankudi",
    "Pune",
    "Pune Cantonment",
    "Puri",
    "Purnia",
    "Purulia",
    "Pusad",
    "Quilandi",
    "Quthbullapur",
    "Rabkavi Banhatti",
    "Raebareli",
    "Raghunathpu",
    "Raichur",
    "Raiganj",
    "Raigarh",
    "Raipur",
    "Rajahmundry",
    "Rajapalayam",
    "Rajarhat-Gopalpore",
    "Rajendranagar",
    "Rajgarh",
    "Rajkot",
    "Rajnandgaon",
    "Rajpur Sonarpore",
    "Rajpura",
    "Rajsamand",
    "Ramachandrapuram",
    "Ramagundam",
    "Ramanagaram",
    "Ramanathapuram",
    "Ramgarh",
    "Ramjibanpore",
    "Rampur",
    "Rampurhat",
    "Ranaghat",
    "Ranchi",
    "Ranibennur",
    "Raniganj",
    "Ranip",
    "Ratangarh",
    "Rath",
    "Ratlam",
    "Ratnagiri",
    "Raurkela",
    "Rayachoti",
    "Rayadurg",
    "Rayagada",
    "Renukoot",
    "Rewa",
    "Rewari",
    "Rishikesh",
    "Rishra",
    "Robertson Pet",
    "Rohtak",
    "Roorkee",
    "Rudrapur",
    "S.A.S. Nagar",
    "Sagar",
    "Sagar",
    "Saharanpur",
    "Saharsa",
    "Sahaswan",
    "Sahibganj",
    "Sainthia",
    "Salem",
    "Samalkota",
    "Samastipur",
    "Sambalpur",
    "Sambhal",
    "Sangamner",
    "Sangareddy",
    "Sangli (Miraj)",
    "Sangrur",
    "Sankarankoil",
    "Santipur",
    "Santirbazar",
    "Sardarshahar",
    "Sarni",
    "Sasaram",
    "Satara",
    "Satna",
    "Sattenapalle",
    "Saunda",
    "Savarkundla",
    "Sawai madhopur",
    "Secunderabad",
    "Sehore",
    "Seoni",
    "Serampore",
    "Serchhip",
    "Serilingampalle",
    "Shahabad",
    "Shahabad",
    "Shahdol",
    "Shahjahanpur",
    "Shajapur",
    "Shamli",
    "Shegaon",
    "Sheopur",
    "Sherkot",
    "Shikohabad",
    "Shillong",
    "Shimla",
    "Shimoga",
    "Shirpur",
    "Shivpuri",
    "Shrirampur",
    "Sibsagar",
    "Siddipet",
    "Sidhpur",
    "Sikandrabad",
    "Sikar",
    "Silchar",
    "Siliguri",
    "Silvassa",
    "Sindhnur",
    "Sindri",
    "Singrauli",
    "Sira",
    "Sirhind",
    "Sirsa",
    "Sirsi",
    "Sirsilla",
    "Sitamarhi",
    "Sitapur",
    "Sivakasi",
    "Siwan",
    "Solan",
    "Solapur",
    "Sonamukhi",
    "Sonepat",
    "Sopore",
    "South Dum Dum",
    "Sri Ganganagar",
    "Sri Muktsar Sahib",
    "Srikakulam",
    "Srikalahasti",
    "Srinagar",
    "Srivilliputhur",
    "Sujangarh",
    "Sultanpur",
    "Sunabeda",
    "Sunam",
    "Supaul",
    "Surat",
    "Suratgarh",
    "Surendranagar",
    "Suri",
    "Suryapet",
    "Tadepalligudem",
    "Tadpatri",
    "Taherpur N.A.A",
    "Taki",
    "Taliparamba",
    "Tambaram",
    "Tamluk",
    "Tanda",
    "Tandur",
    "Tanuku",
    "Tarakeswar",
    "Tarn Taran",
    "Teliamura",
    "Tenali",
    "Tenkasi",
    "Tezpur",
    "Thalassery",
    "Thane",
    "Thanesar",
    "Thanjavur",
    "Theni",
    "Thiruvananthapuram",
    "Thiruvarur",
    "Thrippunithura",
    "Thrissur",
    "Tikamgarh",
    "Tilhar",
    "Tindivanam",
    "Tinsukia",
    "Tiptur",
    "Tiruchendur",
    "Tiruchengode",
    "Tiruchirappalli",
    "Tirunelveli",
    "Tirupathur",
    "Tirupati",
    "Tiruppur",
    "Tirur",
    "Tiruvalla",
    "Tiruvannamalai",
    "Tiruvottiyur",
    "Tisra",
    "Titagarh",
    "Tohana",
    "Tonk",
    "Tufanganj",
    "Tumkur",
    "Tundla",
    "Tuni",
    "Tura",
    "Tuticorin",
    "Udaipur",
    "Udgir",
    "Udhampur",
    "Udumalpet",
    "Udupi",
    "Ujhani",
    "Ujjain",
    "Ukhrul",
    "Ulhasnagar",
    "Uluberia",
    "Una",
    "Unjha",
    "Unnao",
    "Upleta",
    "Uppal Kalan",
    "Uran-Islampur",
    "Uttarpara Kotrung",
    "Vadakara",
    "Vadodara",
    "Valparai",
    "Valsad",
    "Vaniyambadi",
    "Vapi",
    "Varanasi",
    "Vasai",
    "Veerappanchatram",
    "Vejalpur",
    "Vellore",
    "Veraval",
    "Vidisha",
    "Vijalpor",
    "Vijayawada",
    "Viluppuram",
    "Vinukonda",
    "Viramgam",
    "Virar",
    "Virudhachalam",
    "Virudhunagar",
    "Visakhpatnam",
    "Visnagar",
    "Vizianagaram",
    "Vrindavan",
    "Wadhwan",
    "Wanaparthi",
    "Wani",
    "Warangal",
    "Wardha",
    "Washim",
    "Yadgir",
    "Yamuna Nagar",
    "Yavatmal",
    "Yelahanka",
    "Yem"
]
breeds.each do |name,pet_name|
    Breed.create(name:name,pet_name:pet_name)
end

cities.each do |title|
    City.create(title:title)
end


